-- Supports the scheduled auto-processing pipeline:
-- - session_progress.feedback_text: one-shot written feedback on a
--   self-directed writing/commentary submission (generated by a scheduled
--   Claude run, not an in-app LLM backend call).
-- - sessions.generated_from_response_at: when a quiz-type session's rounds
--   were last (re)generated from a linked reading session's submitted word
--   list, so the scheduled job can tell whether regeneration is needed.

alter table session_progress add column feedback_text text;
alter table sessions add column generated_from_response_at timestamptz;
